# Docker Compose Configuration for Notion Integration
# Add this service to your existing docker-compose.yml

version: '3.8'

services:
  # Notion API Service - Handles Notion database sync
  notion-service:
    build:
      context: .
      dockerfile: Dockerfile.notion
    container_name: chatstack-notion-service-1
    command: node services/notion-api-server.js
    env_file:
      - .env
    ports:
      - "8200:8200"
    environment:
      # AI-Memory service connection
      - AI_MEMORY_URL=http://ai-memory-host:8100
      - NOTION_API_PORT=8200
      
      # Notion API credentials
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_PARENT_PAGE_ID=${NOTION_PARENT_PAGE_ID}
      
      # Replit connector credentials (for OAuth token refresh)
      - REPLIT_CONNECTORS_HOSTNAME=${REPLIT_CONNECTORS_HOSTNAME}
      - REPL_IDENTITY=${REPL_IDENTITY}
      - WEB_REPL_RENEWAL=${WEB_REPL_RENEWAL}
    extra_hosts:
      - "ai-memory-host:host-gateway"
    networks:
      - chatstack_appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  chatstack_appnet:
    external: true
