# Docker Compose for NeuroSphere Voice / ChatStack - Unified Architecture
# All services run in single chatstack-network for consistent DNS-based communication

services:
  # ────────────────────────────────────────────────────────
  # Nginx Reverse Proxy (Port 80/443)
  # ────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    container_name: chatstack-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/voice-theinsurancedoctors-com.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./static:/var/www/static:ro
    depends_on:
      - web
      - orchestrator
      - ai-memory
    restart: always
    networks:
      - chatstack-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ────────────────────────────────────────────────────────
  # ChatStack Web Admin (Flask on Port 5000)
  # ────────────────────────────────────────────────────────
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatstack-web
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 --threads 4 --timeout 120 --reuse-port --reload main:app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./static:/app/static:rw
    depends_on:
      - ai-memory
    restart: always
    networks:
      - chatstack-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ────────────────────────────────────────────────────────
  # ChatStack Orchestrator (FastAPI on Port 8001)
  # ────────────────────────────────────────────────────────
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatstack-orchestrator
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./static:/app/static:rw
    restart: always
    networks:
      - chatstack-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # ────────────────────────────────────────────────────────
  # AI-Memory Service runs EXTERNALLY at /opt/ai-memory
  # Not included in this docker-compose - runs as separate service
  # ChatStack services connect to it at http://127.0.0.1:8100
  # ────────────────────────────────────────────────────────

  # ────────────────────────────────────────────────────────
  # Status Monitor (Health Checker)
  # ────────────────────────────────────────────────────────
  # Temporarily disabled - needs psutil in requirements.txt
  # status-monitor:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: chatstack-status-monitor
  #   command: python3 scripts/status_monitor.py --config config/monitor.yml --interval 30
  #   depends_on:
  #     - nginx
  #     - web
  #     - orchestrator
  #     - ai-memory
  #   restart: always
  #   networks:
  #     - chatstack-network
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"
  #       max-file: "2"

# ────────────────────────────────────────────────────────
# Unified Docker Network for All Services
# ────────────────────────────────────────────────────────
networks:
  chatstack-network:
    driver: bridge
    name: chatstack-network
